### ISSUE TITLE
Logstash parser error

### ISSUE THREAD

**Issue by Zer0d0y** [hardenedlinux/Debian-GNU-Linux-Profiles#30]
#### With this settings,All Bro logs will be under Index bro-xxx*,
```shell
~/src# cat > /etc/logstash/conf.d/bro-software.conf << EOF 
input {
	kafka {
		topics => ["software"]
		group_id => "bro_logstash"
     		bootstrap_servers => "192.168.1.147:9092"
     		codec => json
     		auto_offset_reset => "earliest"
   	}
}

output {
	elasticsearch {
     		hosts => ["192.168.1.142:9200"]
		index => "bro-software"
		document_type => "software"
   	}
}
```
From:https://github.com/hardenedlinux/Debian-GNU-Linux-Profiles/blob/master/NSM/docs/ELK_with_bro_ID_doc.mkd#create-new-logstash-configuration

**As you can see here,**
[https://raw.githubusercontent.com/hardenedlinux/Debian-GNU-Linux-Profiles/master/NSM/docs/image/create_pattern_5.png](url)
```shell
AA,RA,RD,TC...,should not be here
```

**Comment by GTrunSec** [comment]
Debuging ways:
Did you get software topic from kafka?
- [ ] bash /opt/kafka/kafka_2.12-1.0.0/bin/kafka-console-consumer.sh –bootstrap-server localhost:9092 –topic software

- [ ] Installed  https://github.com/apache/metron-bro-plugin-kafka and loaded https://github.com/hardenedlinux/Debian-GNU-Linux-Profiles/blob/master/NSM/sensor/bro/scripts/bro-kafka.bro 

you should delete Index which was the first time generated data. Then restart and loaded conf files.
- [ ]  systemctl restart  logstash.service

**Comment by Zer0d0y** [comment]
#### Thanks
It's not working

#### 1.From:https://github.com/hardenedlinux/Debian-GNU-Linux-Profiles/blob/master/NSM/docs/ELK_with_bro_ID_doc.mkd#create-new-logstash-configuration

https://imgur.com/xpQZa1f
https://imgur.com/NUMAzdj

#### 2.From your testing http conf
https://imgur.com/gfoDjMa
https://imgur.com/59SYiPL

#### During my testing,I have moved all data in ELK Stack.

**Comment by GTrunSec** [comment]
I did't get these fields from kibana. Everything looks as good.

- sudo broctl
 -deploy
**/usr/local/bro/logs/current/loaded_scripts.log**
`{"name":"/usr/local/bro/lib/bro/plugins/APACHE_KAFKA/lib/bif/__load__.bro"}
{"name":"  /usr/local/bro/lib/bro/plugins/APACHE_KAFKA/lib/bif/kafka.bif.bro"}
{"name":"/usr/local/bro/lib/bro/plugins/APACHE_KAFKA/scripts/__load__.bro"}
{"name":"  /usr/local/bro/lib/bro/plugins/APACHE_KAFKA/scripts/init.bro"}
 {"name":"    /home/gtrun/src/test/bro-kafka.bro"}
{"name":"      /home/gtrun/src/metron-bro-plugin-kafka/scripts/Apache/Kafka/__load__.bro"}
{"name":"        /home/gtrun/src/metron-bro-plugin-kafka/scripts/Apache/Kafka/logs-to-kafka.bro"}`




 - sudo systemctl status kafka.service
● kafka.service - Kafka Service
   Loaded: loaded (/etc/systemd/system/kafka.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-09-08 18:30:54 EDT; 8s ago
 Main PID: 15761 (java)
    Tasks: 84 (limit: 4915)
   CGroup: /system.slice/kafka.service
           └─15761 java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=3

- sudo systemctl status zookeeper.service
● zookeeper.service - Coordination service for distributed applications
   Loaded: loaded (/lib/systemd/system/zookeeper.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-09-07 01:30:15 EDT; 1 day 17h ago
 Main PID: 784 (java)

- replay pcap
`gtrun@lab:/usr/local/bro/logs/current % sudo tcpreplay -i ens192 -tK --loop 10 ~/packet/2018-01-02-fake-Flash-player-installs-coinminer-malware.pcap``
`
*OUTPUT*
> {"ts":1536444959.900149,"uid":"CwZZA64SqXR3v279p8","id.orig_h":"10.1.2.102","id.orig_p":49986,"id.resp_h":"104.27.152.183","id.resp_p":80,"trans_depth":1,"method":"GET","host":"5chrup56.ru","uri":"/?W3hmqY\u0026sub_id_2=zv73e4a40af00b11e78d3b063e70912a684ff9bf0a5f8c41ca9867d782a0403934026350c6b3f7e82428","referrer":"http://use.india-abc.com/zcredirect?visitid=73e4a40a-f00b-11e7-8d3b-063e70912a68\u0026type=js\u0026browserWidth=784\u0026browserHeight=291\u0026iframeDetected=false","version":"1.1","user_agent":"Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko","request_body_len":0,"response_body_len":0,"status_code":302,"status_msg":"Moved Temporarily","tags":[]}

- I changed kafka log store.
`sudo sed -i '/^log.dirs/{s/=.*//;}' /opt/kafka/config/server.properties
sudo sed -i 's/^log.dirs/log.dirs=\/var\/lib\/kafka/data/' /opt/kafka/config/server.properties`

- moved logstash conf & template.json


`gtrun@lab:/etc/logstash/conf.d % sudo mv ~/src/Debian-GNU-Linux-Profiles/NSM/ELK/conf/test/bro_http.conf .`

`sudo mv ~/src/Debian-GNU-Linux-Profiles/NSM/ELK/conf/test/bro-http-template.json .`

- modified bro_http.conf  IP addr
 Then restarted logstash `sudo systemctl restart logstash.service`

 **Finally, check kibana Index**
![image](https://user-images.githubusercontent.com/21156405/45259373-269fe900-b380-11e8-9458-31f20200571f.png)


![image](https://user-images.githubusercontent.com/21156405/45259384-71b9fc00-b380-11e8-8464-9f8ec315bb57.png)

![image](https://user-images.githubusercontent.com/21156405/45259784-c4e47c80-b389-11e8-8a65-e1f48479ab01.png)


![image](https://user-images.githubusercontent.com/21156405/45259788-e04f8780-b389-11e8-910b-f996cc474e5d.png)

I will be upload pinted bro-kafka_filter.bro & template & install_SHELL no longer.

**Comment by Zer0d0y** [comment]
Thanks for you help,It's work **NOW**! (Sorry,I forgot to add a template during my last test.)

Also a working example without templates,Maybe usefull for You.

**Bro configuration:**
```shell
echo "redef Kafka::tag_json = T;" >> /usr/local/bro/share/bro/site/local.bro
# Ref:
https://github.com/tianyulab/Threat_Hunting_with_ELK/blob/master/Bro/Deploy_Kafka_for_Bro.sh#L91
```

**Logstash configuration:**
```shell
cat > /etc/logstash/conf.d/bro-http.conf << EOF
input {
	kafka {
		topics => ["http"]
		group_id => "bro_logstash"
     		bootstrap_servers => "10.42.94.92:9092"
     		codec => json
     		type => "http"
     		auto_offset_reset => "earliest"
	}
}
output {
	if [type] == "http" {
		elasticsearch {
			hosts => ["192.168.8.112:9200"]
			index => "bro-http-%{+YYYY.MM.dd}"
		}
	}
}
EOF

# Ref:
https://github.com/tianyulab/Threat_Hunting_with_ELK/blob/master/Bro/Deploy_Kafka_for_Bro.sh#L182
```
