### ISSUE TITLE
./bin/syz-extract -os linux -arch arm64 -sourcedir "/xxxx/android/kernel/msm-4.19" -builddir "/xxxx/android/kernel/msm-4.19" proc_operation.txt

### ISSUE THREAD

**Issue by yzj509** [hardenedlinux/Debian-GNU-Linux-Profiles#46]
./bin/syz-extract -os linux -arch arm64 -sourcedir "/xxxx/android/kernel/msm-4.19" -builddir "/xxxx/android/kernel/msm-4.19" proc_operation.txt

generating linux/arm64...
	proc_operation.txt:4:51: len can't be syscall return
proc_operation.txt:5:51: len can't be syscall return

how to fix it？

**Comment by citypw** [comment]
Dear @yzj509 

S0rry, we're not technical support for customized fuzzer on Android. I prefer not to spend any of our time to help this kind of bug report( w/o/ context, description, reproducible steps, etc). Otherwise, could you please be a little honest here to use your true identity? No offense, we really don't want to deal with id like "horseFucker123":

https://github.com/hardenedlinux/harbian-qa/issues/31

I personally don't oppose any forms of anonymous but we should be cautions to help any employees from big corps.
